name: Deploy DynamoDB SAM Template

on:
    push:
        branches:
            - main

env:
    AWS_REGION: eu-central-1
    STACK_NAME: todo-dynamodb-stack

jobs:
    deploy:
        runs-on: ubuntu-latest

        steps:
            - name: Checkout code
              uses: actions/checkout@v3

            - name: Configure AWS Credentials
              uses: aws-actions/configure-aws-credentials@v1
              with:
                  aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
                  aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
                  aws-region: ${{ secrets.AWS_REGION }}

            - name: Install SAM CLI
              run: |
                  pip install aws-sam-cli

            - name: SAM Validate
              run: |
                  sam validate --template template.yml

            - name: SAM Build
              run: |
                  sam build --template template.yml

            - name: SAM Deploy
              run: |
                  sam deploy \
                    --template-file template.yml \
                    --stack-name ${{ env.STACK_NAME }} \
                    --region ${{ secrets.AWS_REGION }} \
                    --capabilities CAPABILITY_IAM \
                    --no-confirm-changeset \
                    --no-fail-on-empty-changeset
